namespace Services.Enums
{
    public enum ValidationResult
    {
        OK,
        BalanceTooLow,
        IncorrectAmount,
        NoAccountFound,
        DateInPast,
        NoReceivingAccountFound,
        MissingGivenName,
        MissingSurname,
        MissingStreetAddress,
        MissingCity,
        MissingZipCode,
        MissingCountry,
        MissingGender,
        MissingBirthday,
        InvalidBirthday,
        MissingNationalId,
        MissingPhone,
        MissingEmail,
        InvalidCountry,
        InvalidTelephoneCountryCode,
        CustomerNotFound,
        UserNotFound,
        NoRoleFound,
        NoSelectedRole,
        InvalidRole,
        CannotDeleteSelf,
        NoSelectedFrequency
    }
}
